# Generated by Django 2.2.12 on 2020-05-30 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_remove_profile_image"),
    ]

    operations = [
        migrations.DeleteModel(name="Profile",),
    ]
