# Generated by Django 2.2.12 on 2020-05-23 16:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20200523_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
