# Generated by Django 2.2.12 on 2020-05-25 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0008_product_in_stock"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="for_sale",
            field=models.BooleanField(default=True),
        ),
    ]
