# Generated by Django 2.2.12 on 2020-05-25 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0009_product_for_sale"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(upload_to="product_pics"),
        ),
    ]
