# Generated by Django 2.2.12 on 2020-05-29 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0020_customer_stripe_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="transaction_id",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
